import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Check, Phone } from "lucide-react";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { JsonLd } from "@/components/json-ld";
import { services } from "@/lib/services";
import { site } from "@/lib/site";
import { breadcrumbSchema, createPageMetadata } from "@/lib/seo";

export const metadata:Metadata=createPageMetadata({title:"Our Services | VantexWeb",description:"Explore custom web design, redesign, landing pages, AI chatbots, SEO, and performance services built for growing businesses.",path:"/services/"});

const serviceSchema={"@context":"https://schema.org","@type":"OfferCatalog","@id":`${site.url}/services/#catalog`,name:"VantexWeb Services",url:`${site.url}/services/`,itemListElement:services.map((service)=>({"@type":"Offer",itemOffered:{"@type":"Service","@id":`${site.url}/services/#${service.slug}`,url:`${site.url}/services/#${service.slug}`,name:service.name,description:service.shortDescription,provider:{"@id":`${site.url}/#organization`},areaServed:"Worldwide"}}))};
const standards=["Responsive across real screen sizes","Accessible, semantic foundations","Speed-conscious production build","Technical SEO essentials","Clear calls to action","Transparent launch handoff"];

export default function ServicesPage(){return <><Navbar/><main id="main-content"><section id="top" className="page-hero services-page-hero"><div className="shell page-hero-grid"><h1>Web services<br/><span>that work as one.</span></h1><div><p>Design, development, AI, SEO, and performance—connected around one goal: a website that moves your business forward.</p><div className="page-hero-actions"><Link href="#service-details" className="button">Explore the services <ArrowRight size={18}/></Link><Link href="/contact" className="button-secondary">Request a Website Quote</Link></div></div></div></section><section className="services-standards"><div className="shell"><div className="services-standard-heading"><h2>What every website engagement includes</h2><p>Responsive behavior, usability, and sound technical foundations are standards—not separate upgrades.</p></div><div className="services-standard-grid">{standards.map((standard,index)=><span key={standard}><i>{String(index+1).padStart(2,"0")}</i>{standard}</span>)}</div></div></section><section id="service-details" className="services-detail-list"><div className="shell">{services.map((service)=><article id={service.slug} className="service-detail" key={service.slug} data-reveal><div className="service-detail-lead"><span className="service-detail-number">{service.number}</span><h2>{service.name}</h2><p>{service.detail}</p><Link href="/contact" className="text-link">Discuss this service <ArrowRight size={17}/></Link></div><div className="service-detail-scope"><div className="service-includes"><h3>What the engagement can include</h3><ul>{service.includes.map((item)=><li key={item}><Check size={16}/><span>{item}</span></li>)}</ul></div><div className="service-fit"><span>Best fit</span><p>{service.bestFor}</p></div><div className="service-outcome"><span>What this should improve</span><p>{service.outcome}</p></div></div></article>)}</div></section><section className="services-closing"><div className="shell services-closing-layout"><div><h2>Not sure which service fits?</h2><p>Tell us what the website needs to accomplish. We will recommend the leanest scope that can do the job well—without padding the project with work you do not need.</p></div><div><Link href="/contact" className="button">Get My Free Website Quote <ArrowRight size={18}/></Link><a href={`tel:${site.phoneHref}`} className="button-secondary"><Phone size={17}/>{site.phoneDisplay}</a></div></div></section></main><Footer/><JsonLd data={[serviceSchema,breadcrumbSchema("Services","/services/")]}/></>}
