import type { Metadata } from "next";
import { ArrowDown, Check, Mail, Phone } from "lucide-react";
import { Navbar } from "@/components/navbar";
import { Footer } from "@/components/footer";
import { ContactForm } from "@/components/contact-form";
import { site } from "@/lib/site";
import { breadcrumbSchema,createPageMetadata } from "@/lib/seo";

export const metadata:Metadata=createPageMetadata({title:"Get a Free Website Quote | VantexWeb",description:"Tell us about your project and get a free website quote for custom web design, redesign, landing pages, SEO, or AI integration.",path:"/contact/"});
const contactSchema=[{"@context":"https://schema.org","@type":"ContactPage",name:"Contact VantexWeb",url:`${site.url}/contact/`,description:"Contact VantexWeb about a web design and development project.",mainEntity:{"@id":`${site.url}/#organization`}},breadcrumbSchema("Contact","/contact/")];
const nextSteps=[["01","We read the context","Your message is reviewed as a real project brief—not dropped into an automated sales sequence."],["02","We identify the useful questions","If something important is unclear, we ask before recommending features, scope, or technology."],["03","You get a practical next step","If the project is a fit, we outline the recommended direction and what is needed to move toward a proposal."]] as const;

export default function ContactPage(){return <><Navbar/><main><section id="top" className="page-hero contact-page-hero"><div className="shell contact-hero-layout"><div><h1>Start with the problem.<br/><span>Not a sales pitch.</span></h1><p>Tell us what the website needs to improve, who it needs to reach, and what is getting in the way today. We will use that context to recommend a sensible next step.</p><a href="#project-brief" className="contact-hero-jump">Share the project brief <ArrowDown size={18}/></a></div><div className="contact-direct"><h2>Contact VantexWeb directly</h2><a href={`mailto:${site.email}`}><Mail size={18}/><span><small>Email</small>{site.email}</span></a><a href={`tel:${site.phoneHref}`}><Phone size={18}/><span><small>Phone</small>{site.phoneDisplay}</span></a><p><Check size={15}/>No generic audit. No pressure script. Just a focused conversation about whether and how we can help.</p></div></div></section><ContactForm standalone/><section className="contact-next-steps"><div className="shell contact-next-layout"><div><h2>What happens after you reach out?</h2><p>A simple process designed to produce clarity before either side commits to a project.</p></div><ol>{nextSteps.map(([number,title,copy])=><li key={number}><span>{number}</span><div><h3>{title}</h3><p>{copy}</p></div></li>)}</ol></div></section></main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(contactSchema).replace(/</g,"\u003c")}}/></>}
