export type PortfolioProject = {
  name: string;
  type: string;
  url: string;
  domain: string;
  image: string;
  alt: string;
  summary: string;
  highlights: readonly string[];
  homeFeatured?: boolean;
};

export const portfolioProjects: readonly PortfolioProject[] = [
  { name:"SUNNYCELLS", type:"Ecommerce wellness website", url:"https://demo-ryze.vercel.app/", domain:"demo-ryze.vercel.app", image:"/portfolio/sunnycells.webp", alt:"SUNNYCELLS Metabolic Morning Blend ecommerce website homepage", summary:"A warm, conversion-focused supplement storefront that turns a daily wellness product into a clear, repeatable morning ritual.", highlights:["Product-led art direction","Subscription-focused CTA","Ingredient storytelling"], homeFeatured:true },
  { name:"Sun Direct Renewable", type:"Solar energy website", url:"https://sundirect.ca/", domain:"sundirect.ca", image:"/portfolio/sun-direct.webp", alt:"Sun Direct Renewable website homepage for Alberta solar services", summary:"A conversion-led solar platform for Alberta homes, businesses, and farms, connecting service discovery with a clear proposal journey.", highlights:["Multi-service architecture","Proposal-focused UX","Local search content"], homeFeatured:true },
  { name:"SoCal Cleaning Company", type:"Local service website", url:"https://socal-cleaning.vercel.app/", domain:"socal-cleaning.vercel.app", image:"/portfolio/socal-cleaning.webp", alt:"SoCal Cleaning Company website homepage", summary:"A bright, trust-first cleaning website that makes services, coverage, and quote requests easy to understand on any screen.", highlights:["Fast quote journey","Service-area messaging","Mobile-first contact"], homeFeatured:true },
  { name:"The Fade Room", type:"Barber studio website", url:"https://the-fade-room-xi.vercel.app/", domain:"the-fade-room-xi.vercel.app", image:"/portfolio/the-fade-room.webp", alt:"The Fade Room VIP Barber Studio website homepage", summary:"A bold, editorial booking experience for an Orange, California barber studio, pairing premium brand direction with services, social proof, and a direct appointment path.", highlights:["Editorial brand system","Booking-focused journey","Review-led trust"], homeFeatured:true },
  { name:"Ultra Roofer Peak Authority", type:"Roofing service website", url:"https://ultra-roofer.vercel.app/", domain:"ultra-roofer.vercel.app", image:"/portfolio/ultra-roofer.webp", alt:"Ultra Roofer Peak Authority Los Angeles roofing website homepage", summary:"A high-contrast Los Angeles roofing website that frames inspections, repairs, and replacements around clear scope, documented work, and fast contact.", highlights:["Inspection-first funnel","Service-area positioning","24-hour contact path"], homeFeatured:true },
  { name:"Sugar In The Morning", type:"Residential cleaning website", url:"https://sugar-in-the-morning.vercel.app/", domain:"sugar-in-the-morning.vercel.app", image:"/portfolio/sugar-in-the-morning.webp", alt:"Sugar In The Morning cleaning service website homepage", summary:"A warm editorial brand experience for a San Angelo cleaning service, balancing personality with a direct path to request a quote.", highlights:["Distinctive brand direction","Service clarity","Call and quote paths"] },
  { name:"Face Shape Detector", type:"Privacy-first AI tool", url:"https://faceshapedetector.online/", domain:"faceshapedetector.online", image:"/portfolio/face-shape-detector.webp", alt:"Free Face Shape Detector website and photo analysis interface", summary:"A guided browser-based tool that helps visitors estimate their face shape and explore practical, search-friendly style guidance.", highlights:["Guided photo analysis","Privacy-first experience","Content library"] },
  { name:"Carspect", type:"AI automotive estimator", url:"https://carspect.pro/", domain:"carspect.pro", image:"/portfolio/carspect.webp", alt:"Carspect car body repair estimate calculator homepage", summary:"A photo-guided repair calculator that turns visible vehicle damage into an itemized preliminary cost range and readable report.", highlights:["Multi-step estimator","Itemized cost logic","Downloadable reports"] },
  { name:"BIBIBOP Nutrition Calculator", type:"Interactive nutrition platform", url:"https://bibibopnutritioncalculator.pro/", domain:"bibibopnutritioncalculator.pro", image:"/portfolio/bibibop-nutrition-calculator.webp", alt:"BIBIBOP Nutrition Calculator bowl builder interface", summary:"An ingredient-level bowl builder that calculates calories, macros, sodium, and allergens as customers assemble their meal.", highlights:["Live nutrition totals","Allergen visibility","Search-led content"] },
  { name:"Taksi Ücreti Hesaplama", type:"Fare calculator and content platform", url:"https://taksiucreti-hesaplama.blog/", domain:"taksiucreti-hesaplama.blog", image:"/portfolio/taksi-ucreti-hesaplama.webp", alt:"Taksi Ücreti Hesaplama city fare calculator homepage", summary:"A Turkish fare-calculation platform that turns city tariff data into clear journey estimates, source records, and local guides.", highlights:["81-city calculator","Source-aware data","Scalable local pages"] },
];
